### ISSUE TITLE
PyPI package lack support for Python > 3.5

### ISSUE THREAD

**Issue by allxone** [astro-pi/python-sense-emu#29]
I'm having some issues building one of my ROS packages that includes your PyPI sense-emu package for testing.
The problem looks to be related with the lack of support for Python 3 versions greater than 3.5 (3.6 looks to be the minimum required by the ROS buildfarm).
I tested your package with Python 3.6 without any issue and I was also able to let sense-hat and sense-emu being included into the rosdep official [index](https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml) via [#25892](https://github.com/ros/rosdistro/pull/25892). I'm now stuck in the pre-release buildfarm process of my [sensehat_ros](https://github.com/allxone/sensehat_ros) package apparently due to this lack of support.

What is required to happen to include Python 3.6 and above into the PyPI programming languages list?

Thanks,
Stefano

**Comment by bennuttall** [comment]
There's no reason you can't use it with Python 3.6. When the project was created, Raspbian shipped with Python 3.5 so I guess at the time it could only claim to support up to 3.5. But it's been used by many on 3.7 as that's what in the current Raspbian.

**Comment by allxone** [comment]
Sorry, my fault.
The issue is not related to the specific version of Python supported. I wrongly supposed the ROS release process would allow for pip package dependencies but this is not possible because they target to create Debian packages (cfr. https://github.com/ros-infrastructure/ros_buildfarm/issues/764).

Thanks Ben for your support,
Stefano
